### PR TITLE
Addition of user programmable clock sync

### PR DESCRIPTION
**Pull request by jonnew**
This PR contains the following modifications:

1. Added a general purpose clock divider module to the code
1. Used the clock divider to generate a sync signal at various ratios of the sample clock
1. Implemented the Wire/Trigger-Ins required to change the clock divide ratio from the open-ephys GUI
1. Wired the new sync signal to the BNC out
1. Added and enforced a .gitignore to get rid of all the ISE vomit in the repository

This PR pairs with this one for the GUI:  https://github.com/open-ephys/GUI/pull/326

### CODE REVIEW

**Comment by aacuevas** [comment]
Hi,

Sorry for taking so long to answer.

Seems like a good addition, I'll have to test that it works on the USB3 branch, though, but I don't see why it shouldn't. I'll probably merge it in a couple of days.

Also, thanks for the ISE cleanup, that was a much needed work.

Aarón.

**Comment by aacuevas** [comment]
Regarding the pause issue we talked on open-ephys/GUI#326 , the dataclk does not stop as it gets straight out of the PLL and is used on other modules. In fact, perhaps it might be better to use it as a clock source on the frequency divider and then use the sample_clk as a sort of edge-triggered enable. Signal lines and clock lines are usually best kept apart, as the FPGA router uses special internal lines for clocks and mixing signals can make the design considerably inneficient. I'll take a good look at the output logs to see if the router complain about this, though.

To pause the output in a low state, I'd use the SPI_running signal as indicator: this signal is 1 when the board is acquiring and 0 when it's paused.

**Comment by jonnew** [comment]
OK, I will look into this. However, its a bit different than the point I was thinking about. Basically, when you press play on the OE GUI, then pause, then play, time is keep continuous. This is a great feature. Basically, time can be concatenated. This means that pressing pause in the GUI should make the sync clock stop in whatever state it was last in. That way, if you have external equipment attached, you don't end up getting an extra sample when the GUI is unpaused. This is how it works now. Great.

However, there is the case that you really want to restart everything. This means resetting the OE recording clock to 00:00. For instance, when switching out animals. In this case:

Is there a way to restart the master clock to 00:00 in the OE GUI without restarting the program? If so, this is the signal that we would want to tie to force the sync signal low in order to 'restart' it.

**Comment by jonnew** [comment]
Is the `dataclk` signal running at the SPI CLK frequency? i.e. 2800 * round-robin sample frequency?

**Comment by aacuevas** [comment]
Ah, I understand now... Actually, the clock on the GUI doesn't reset, but the hardware timestamps Rhythm generates do, so any new acquisition after pausing will start at zero, so it is safe to just zero the sync signal when it stops. (Since the GUI is designed to be input agnostic, its clock is just independent from actual acquisition, but it is not a bad idea to add the ability to reset it)

`dataclk` runs indeed at 2800*sampling frequency. The actual SPI clock (SCLK signal in the code) does not run at that speed. It is not, in fact, even always cycling, as it is off on parts of the cycle of the state machine due to the needs of the SPI protocol (see page 23 of Rhythm datasheet for an example of a cycle).

**Pull request merged**
